window.CipherGapEnglish = {
  "CipherGap — یک لایهٔ خصوصی برای گفتگوهای شما": "CipherGap — A private layer for your conversations",
  "رفتن به محتوای اصلی": "Skip to main content",
  "منو": "Menu",
  "قابلیت‌ها": "Features",
  "نصب افزونه": "Install",
  "آموزش استفاده": "How it works",
  "پرسش‌ها": "Questions",
  "متن‌باز": "Open source",
  "نسخهٔ": "Version",
  "· ظاهری تازه، فایل‌های خصوصی‌تر": "· A fresh look, more private files",
  "حریم خصوصی، در مرورگر خودتان": "Privacy, in your browser",
  "همان گفتگوها.": "Same conversations.",
  "یک لایهٔ خصوصی.": "A private layer.",
  "CipherGap پیام و فایل شما را": "CipherGap encrypts your messages and files",
  "پیش از ارسال": "before sending them",
  "در مرورگر رمزگذاری می‌کند. طرف مقابل با کلید مشترک آن را باز می‌کند؛ ساده، روشن و تحت کنترل شما.": "in your browser. Your partner opens them with your shared key. Simple, clear, and under your control.",
  "نصب و شروع": "Install & start",
  "ببینید چطور کار می‌کند": "See how it works",
  "رمزگذاری محلی": "Local encryption",
  "بدون سرور CipherGap": "No CipherGap server",
  "یک گفتگو، فقط بین شما دو نفر": "A conversation between the two of you",
  "آ": "A",
  "یک دوست": "A friend",
  "کلید مشترک تأیید شده": "Shared key verified",
  "فایل جلسه رو برات بفرستم؟": "Shall I send you the meeting file?",
  "۱۴:۲۱": "14:21",
  "حتماً، با CipherGap بفرست 🙂": "Sure, send it with CipherGap 🙂",
  "۱۴:۲۲": "14:22",
  "آنچه پیام‌رسان دریافت می‌کند": "What the messenger receives",
  "متن اصلی، پشت یک کلید مشترک": "Your original text, behind a shared key",
  "پیام بعدی شما…": "Your next message…",
  "کلید تأیید شد": "Key verified",
  "مقایسهٔ کد، روی هر دو دستگاه": "Compare the code on both devices",
  "رمزگذاری پیش از ارسال": "Encrypted before sending",
  "نمایش آموزشی؛ پیام واقعی ارسال نمی‌شود.": "Illustration only; no real message is sent.",
  "برای گفتگوهای روزمرهٔ شما": "For your everyday conversations",
  "شروع با بله؛ مسیر توسعه برای پیام‌رسان‌های بیشتر.": "Starting with Bale, with more messengers on the roadmap.",
  "ب": "B",
  "بله": "Bale",
  "فعال": "Available",
  "ا": "E",
  "ایتا": "Eitaa",
  "در برنامهٔ توسعه": "On the roadmap",
  "ر": "R",
  "روبیکا": "Rubika",
  "ت": "T",
  "تلگرام": "Telegram",
  "و": "W",
  "واتساپ": "WhatsApp",
  "کمتر پیچیدگی، بیشتر کنترل": "Less complexity. More control.",
  "برای پیام‌ها. برای فایل‌ها.": "For messages. For files.",
  "برای خیال راحت‌تر.": "For more peace of mind.",
  "افزونه کنار ابزارهای آشنای پیام‌رسان قرار می‌گیرد.": "CipherGap sits beside the messenger tools you already know.",
  "شما تصمیم می‌گیرید چه چیزی را رمزگذاری کنید.": "You decide what to encrypt.",
  "پیامی که با کلید باز می‌شود": "A message that opens with a key",
  "با دکمهٔ": "Use",
  "، متن پیش از ارسال با": " to encrypt your text with",
  "رمزگذاری می‌شود. باز شدن خودکار پیام‌ها برای هر گفتگو قابل تنظیم است.": "before sending. Set automatic message decryption separately for each chat.",
  "متن اصلی در مرورگر پردازش می‌شود": "Your original text is processed in your browser",
  "فایل بفرستید، با همان سادگی": "Send files, just as easily",
  "انتخاب فایل، پیش‌نمایش رمز‌شده و ارسال. گیرنده می‌تواند فایل را از همان پیام رمزگشایی کند یا دریافت خودکار را روشن کند.": "Choose a file, preview the encrypted attachment, and send. Your partner can decrypt it from the message or enable automatic receiving.",
  "نام اصلی فایل پس از رمزگشایی حفظ می‌شود": "Original filenames are restored after decryption",
  "یک کلید برای هر گفتگو": "One key for each chat",
  "تبادل کلید با": "Exchange a key using",
  "انجام می‌شود. کد شش‌رقمی را از یک راه مطمئن مقایسه کنید و روی هر دو دستگاه تأیید کنید.": ". Compare the six-digit code over a trusted channel and verify on both devices.",
  "هشدار هنگام تغییر اثر انگشت طرف مقابل": "An alert when your partner’s fingerprint changes",
  "اولین قدم، همین‌جاست": "Your first step starts here",
  "چند دقیقه تا": "A few minutes to",
  "اولین پیام رمز‌شده.": "your first encrypted message.",
  "افزونه را روی مرورگر دسکتاپ هر دو نفر نصب کنید. نسخهٔ فعلی به‌صورت دستی نصب می‌شود.": "Install CipherGap on both people’s desktop browsers. The current version is installed manually.",
  "مشاهدهٔ کد در GitHub": "View the code on GitHub",
  "نصب فایرفاکس از طریق ابزار توسعه موقت است. برای نصب دائمی در نسخهٔ استاندارد، بستهٔ امضاشدهٔ موزیلا لازم است.": "Installation through Firefox’s developer tools is temporary. Permanent installation in standard Firefox requires a Mozilla-signed package.",
  "نصب دستی در کروم": "Manual installation in Chrome",
  "۱": "1",
  "دانلود و استخراج": "Download & extract",
  "سورس افزونه را دانلود کنید و فایل ZIP را از حالت فشرده خارج کنید.": "Download the extension source and extract the ZIP file.",
  "دانلود نسخهٔ کروم": "Download for Chrome",
  "۲": "2",
  "صفحهٔ افزونه‌ها را باز کنید": "Open the extensions page",
  "آدرس زیر را در نوار آدرس مرورگر وارد کنید و": "Enter the address below in your browser’s address bar and enable",
  "را روشن کنید.": ".",
  "کپی": "Copy",
  "۳": "3",
  "پوشهٔ افزونه را انتخاب کنید": "Select the extension folder",
  "روی": "Click",
  "کلیک کنید و پوشهٔ داخلی": " and select the inner",
  "را که فایل": " folder containing",
  "دارد انتخاب کنید.": ".",
  "۴": "4",
  "بله وب را تازه‌سازی کنید": "Refresh Bale Web",
  "وارد حساب شوید، گفتگو را باز کنید و لوگوی CipherGap را از نوار مرورگر انتخاب کنید.": "Sign in, open your conversation, and select the CipherGap logo from your browser toolbar.",
  "نصب آزمایشی در فایرفاکس ۱۴۰ یا جدیدتر": "Try it in Firefox 140 or later",
  "نسخهٔ فایرفاکس را دانلود کنید": "Download the Firefox version",
  "سورس شاخهٔ": "Download and extract the source from the",
  "را دانلود و استخراج کنید.": " branch.",
  "دانلود نسخهٔ فایرفاکس": "Download for Firefox",
  "ابزار توسعهٔ افزونه‌ها را باز کنید": "Open the add-on developer tools",
  "آدرس زیر را در نوار مرورگر وارد کنید.": "Enter the address below in your browser’s address bar.",
  "افزونه را بارگذاری کنید": "Load the extension",
  "بزنید و فایل": " and choose",
  "را انتخاب کنید. دسترسی به بله وب را در صورت درخواست مرورگر تأیید کنید.": ". Allow access to Bale Web if Firefox asks you.",
  "گفتگو را باز کنید": "Open your conversation",
  "بله وب را تازه‌سازی کنید. نصب موقت با بستن و باز کردن فایرفاکس حذف می‌شود و باید دوباره بارگذاری شود.": "Refresh Bale Web. Temporary installations are removed when Firefox restarts and must be loaded again.",
  "از نصب تا اولین گفتگو": "From installation to your first conversation",
  "با هم شروع کنید.": "Start together.",
  "سه قدم روشن برای شما و طرف مقابل.": "Three clear steps for you and your partner.",
  "نام دکمه‌ها مطابق رابط انگلیسی افزونه است.": "Button names below match the extension’s English interface. Choose Persian or English from its language menu.",
  "یک درخواست، یک کلید مشترک": "One request, one shared key",
  "هر دو نفر همان گفتگو را باز کنید. در بخش": "Both people open the same conversation. Under",
  "بزنید. طرف مقابل با": ". Your partner chooses",
  "درخواست را می‌پذیرد.": "to accept the request.",
  "شش رقم را مقایسه کنید": "Compare the six digits",
  "کد نمایش‌داده‌شده را در تماس مطمئن یا حضوری مقایسه کنید. اگر یکسان بود، هر دو نفر": "Compare the displayed code over a trusted call or in person. If it matches, both people choose",
  "را انتخاب کنید. اگر نبود،": ". If it differs, choose",
  "را بزنید.": ".",
  "فرستادن کد فقط در همان چت، هویت طرف مقابل را تأیید نمی‌کند.": "Sending the code only in the same chat does not verify your partner’s identity.",
  "بنویسید. رمزگذاری کنید. بفرستید.": "Write. Encrypt. Send.",
  "متن را در کادر بله بنویسید و از": "Write in Bale’s composer and use",
  "استفاده کنید. طرف مقابل با کلید مشترک پیام را باز می‌کند؛ باز شدن خودکار از": ". Your partner opens the message with the shared key. Automatic decryption is configurable under",
  "قابل تنظیم است.": ".",
  "دکمهٔ معمولی ارسال بله، متن را بدون رمزگذاری CipherGap می‌فرستد.": "Bale’s ordinary send button sends text without CipherGap encryption.",
  "وضعیت": "The",
  "یعنی کلید و اثر انگشت تأیید شده‌اند.": "status means the key and fingerprint have been verified.",
  "فراتر از چند کلمه": "Beyond a few words",
  "فایل‌ها هم": "Files are part",
  "بخشی از گفتگو هستند.": "of the conversation, too.",
  "انتخاب:": "Choose:",
  "از": "Pick your files from",
  "یا دکمهٔ": "or the",
  "داخل گفتگو، فایل را انتخاب کنید.": "button in your conversation.",
  "ارسال:": "Send:",
  "پیش‌نمایش بله فایل با پسوند": "Bale’s preview shows files ending in",
  "را نشان می‌دهد. ارسال را تأیید کنید.": ". Confirm to send them.",
  "دریافت:": "Receive:",
  "طرف مقابل": "Your partner chooses",
  "را می‌زند؛ فایل با نام اصلی ذخیره می‌شود.": "and the file downloads with its original name.",
  "دریافت خودکار، به انتخاب شما": "Automatic receiving, your choice",
  "گزینهٔ": "Enable",
  "را برای هر گفتگو جدا روشن کنید. فایل‌های جدید هنگام باز بودن آن گفتگو دریافت و رمزگشایی می‌شوند.": "separately for each chat. New files are received and decrypted while that conversation is open.",
  "تا ۱۰۰ مگابایت در هر انتخاب و هر فایل دریافتی. برای دانلود مستقیم ناموفق، فایل": "Up to 100 MB per selection and incoming file. If direct downloading fails, download the",
  "را از بله دانلود کنید و": "file from Bale and choose",
  "را انتخاب کنید.": ".",
  "شفافیت، بخشی از اعتماد است": "Transparency is part of trust",
  "کلید شما.": "Your key.",
  "مرورگر شما.": "Your browser.",
  "انتخاب شما.": "Your choice.",
  "CipherGap سرور پردازش جداگانه‌ای ندارد. رمزگذاری و رمزگشایی در مرورگر انجام می‌شود؛ پیام‌رسان همچنان فایل و متن رمز‌شده را جابه‌جا می‌کند.": "CipherGap has no separate processing server. Encryption and decryption happen in your browser; the messenger still transports encrypted text and files.",
  "رمزگذاری پیام و فایل": "Message and file encryption",
  "ساخت کلید مشترک": "Shared key generation",
  "قابل بررسی در GitHub": "Review the code on GitHub",
  "این لایه، فرادادهٔ گفتگو را پنهان نمی‌کند و جای امنیت دستگاه یا بررسی هویت طرف مقابل را نمی‌گیرد. کلید را فقط در یک مرورگر و دستگاه قابل اعتماد نگه دارید.": "This layer does not hide conversation metadata or replace device security and identity verification. Keep keys on a browser and device you trust.",
  "کد رمزگذاری را ببینید": "Read the encryption code",
  "پیش از شروع": "Before you begin",
  "چند پاسخ": "A few answers",
  "به سؤال‌های شما.": "to your questions.",
  "اگر چیزی درست کار نکرد، اینجا شروع خوبی است.": "If something does not work, start here.",
  "الان روی کدام پیام‌رسان‌ها کار می‌کند؟": "Which messengers work today?",
  "نسخهٔ فعلی فقط از بله وب پشتیبانی می‌کند. ایتا، روبیکا، تلگرام و واتساپ در برنامهٔ توسعه هستند و هنوز فعال نیستند.": "The current version supports Bale Web. Eitaa, Rubika, Telegram, and WhatsApp are on the roadmap and are not active yet.",
  "طرف مقابل هم باید افزونه را نصب کند؟": "Does my partner need the extension too?",
  "بله. هر دو نفر به افزونه و کلید مشترک همان گفتگو نیاز دارند. با تبادل کلید و مقایسهٔ کد شش‌رقمی شروع کنید.": "Yes. Both people need CipherGap and the shared key for that chat. Start with a key exchange and compare the six-digit code.",
  "آیا همهٔ پیام‌ها خودکار رمزگذاری می‌شوند؟": "Are all messages encrypted automatically?",
  "خیر. برای متن از دکمهٔ Encrypt استفاده کنید. ارسال عادی بله، عادی باقی می‌ماند. فایل‌ها هنگام وجود کلید گفتگو پیش از ارسال رمزگذاری می‌شوند.": "No. Use Encrypt for text and Encrypted file for files. Bale’s ordinary send and attachment controls stay ordinary.",
  "اگر اثر انگشت تغییر کرد یا کدها یکسان نبودند چه کنم؟": "What if the fingerprint changes or the codes differ?",
  "تغییر اثر انگشت می‌تواند بعد از تبادل مجدد کلید یا تغییر دستگاه رخ دهد. قبل از ادامه، هویت طرف مقابل را از یک راه مطمئن بررسی کنید. در صورت تفاوت کد، گزینهٔ Codes don’t match را انتخاب کنید و دوباره تبادل کلید انجام دهید.": "A fingerprint can change after a new exchange or device change. Check your partner’s identity over a trusted channel before continuing. If codes differ, choose Codes don’t match and start a new exchange.",
  "چرا یک پیام قدیمی باز نمی‌شود؟": "Why does an old message not decrypt?",
  "برای باز کردن آن، کلید زمان ارسال لازم است. تعویض یا حذف کلید ممکن است باعث شود پیام‌ها و فایل‌های قبلی با کلید فعلی باز نشوند. قبل از حذف کلید، این موضوع را در نظر بگیرید.": "You need the key used when it was sent. Replacing or deleting a key may prevent old messages and files from opening with the current key. Consider this before deleting a key.",
  "چرا دریافت خودکار فایل کار نمی‌کند؟": "Why does automatic file receiving not work?",
  "کلید گفتگو و گزینهٔ Receive files automatically را بررسی کنید. این قابلیت فقط برای فایل‌های جدیدِ دریافتی هنگام باز بودن گفتگو است. فایل‌های قدیمی را با Decrypt & download باز کنید؛ برای دریافت مستقیم ناموفق، از انتخاب فایل دانلودشده استفاده کنید.": "Check the chat key and Receive files automatically setting. It applies only to new incoming files while the conversation is open. Use Decrypt & download for older files, or select a downloaded file if direct downloading fails.",
  "افزونه یا دکمه‌های آن را نمی‌بینم؛ چه کنم؟": "I cannot see the extension or its buttons. What should I do?",
  "بله وب را تازه‌سازی کنید، گفتگو را باز کنید، فعال بودن افزونه و مجوز دسترسی به بله وب را بررسی کنید و فقط یک نسخهٔ CipherGap را فعال نگه دارید. نصب موقت فایرفاکس پس از راه‌اندازی دوبارهٔ مرورگر نیاز به بارگذاری مجدد دارد.": "Refresh Bale Web, open a conversation, and check that CipherGap is enabled and has site access. Keep only one CipherGap version active. Temporary Firefox installs must be loaded again after restarting.",
  "گفتگوی بعدی، با یک انتخاب تازه": "Your next conversation, with a new choice",
  "از همان مرورگر شروع کنید.": "Start in the browser you already use.",
  "نسخهٔ ۱.۱.۰ · برای بله وب · کروم و فایرفاکس": "Version 1.2.0 · Bale Web · Chrome & Firefox",
  "راهنمای نصب": "Installation guide",
  "ساخته‌شده برای گفتگوهای خصوصی‌تر. توسعه توسط": "Built for more private conversations. Developed by",
  "علی شریفی": "Ali Sharify",
  "تغییرات نسخه‌ها": "Changelog",
  "گزارش مشکل": "Report an issue",
  "چطور افزونه را غیرفعال کنم؟": "How can I pause the extension?",
  "در Settings گزینهٔ CipherGap enabled را برای توقف همهٔ گفتگوها خاموش کنید؛ Enabled in this chat فقط همان گفتگو را متوقف می‌کند. کلیدها حذف نمی‌شوند. دکمهٔ Pause chat داخل گفتگو هم همین کار را انجام می‌دهد.": "In Settings, turn off CipherGap enabled to pause all chats, or Enabled in this chat to pause this conversation. Keys are kept. The Pause chat button in the conversation does the same.",
  "خیر. برای متن از دکمهٔ Encrypt استفاده کنید. ارسال عادی بله، عادی باقی می‌ماند. برای فایل رمز‌شده، دکمهٔ Encrypted file را انتخاب کنید. دکمهٔ فایل عادی بله، فایل عادی می‌فرستد.": "No. Use Encrypt for text and Encrypted file for files. Bale’s ordinary send and attachment controls stay ordinary.",
  "نام دکمه‌ها مطابق رابط انگلیسی افزونه است. فارسی یا انگلیسی را از منوی زبان افزونه انتخاب کنید.": "Button names below match the extension’s English interface. Choose Persian or English from its language menu.",
  "نسخهٔ ۱.۲.۰ · برای بله وب · کروم و فایرفاکس": "Version 1.2.0 · Bale Web · Chrome & Firefox",
  "CipherGap، ابتدای صفحه": "CipherGap, back to top",
  "منوی اصلی": "Main navigation",
  "انتخاب مرورگر": "Choose your browser",
  "نمایش آموزشی یک پیام رمز‌شده و تأیید کلید": "Illustration of an encrypted message and key verification",
  "کپی آدرس صفحهٔ افزونه‌های کروم": "Copy the Chrome extensions address",
  "کپی آدرس ابزار توسعهٔ فایرفاکس": "Copy the Firefox developer tools address",
  "نمای بخش امنیت CipherGap پس از تأیید کلید مشترک": "CipherGap security screen after shared key verification",
  "صفحهٔ Files با انتخاب فایل امن و تنظیم دریافت خودکار": "Files screen with secure file selection and automatic receiving"
};
