window.CipherGapEnglish = {
  "CipherGap افزونهٔ کامپیوتر و برنامهٔ اندروید برای رمزگذاری پیام و فایل، پیش از ارسال در نسخهٔ وب پیام‌رسان‌هاست. رایگان، متن‌باز و با پردازش روی دستگاه شما.": "CipherGap is a desktop extension and Android app that encrypts messages and files before you send them in web messengers. Free, open source and processed on your device.",
  "CipherGap — پیام و فایل را رمز کن، در همان چت بفرست.": "CipherGap — Encrypt messages and files. Send them in your chat.",
  "همان گفتگوی بله، ایتا یا تلگرام وب؛ پیام و فایل با یک کلید مشترک خوانده می‌شوند.": "Your usual Bale, Eitaa or Telegram Web conversation; messages and files are read with a shared key.",
  "رفتن به محتوای اصلی": "Skip to content",
  "منو": "Menu",
  "منوی اصلی": "Main navigation",
  "چطور کار می‌کند؟": "How it works",
  "داخل برنامه": "Inside the app",
  "نصب": "Install",
  "سوالات رایج": "FAQ",
  "زبان": "Language",
  "دانلود رایگان": "Free download",
  "رمزگذاری برای گفتگوی روزمره": "ENCRYPTION FOR YOUR EVERYDAY CHATS",
  "پیام و فایل را": "Your messages and files.",
  "رمز کن، بفرست.": "Encrypted. Then sent.",
  "CipherGap افزونهٔ کامپیوتر و برنامهٔ اندروید است. پیام و فایل را روی دستگاه شما رمز می‌کند؛ آن‌ها را در همان چت می‌فرستید و طرف مقابل با CipherGap و کلید مشترک بازشان می‌کند.": "CipherGap is a desktop extension and Android app. It encrypts messages and files on your device. Send them in your usual chat; your partner opens them with CipherGap and your shared key.",
  "نسخهٔ مناسبم را نصب کنم": "Install on my device",
  "اول ببینم چطور کار می‌کند": "See how it works",
  "رایگان و متن‌باز": "Free & open source",
  "کلیدها روی دستگاه شما": "Keys stay on your device",
  "نیاز به نصب برای هر دو نفر": "Both people need CipherGap",
  "انتقال کلید و تنظیمات، حالا با QR": "Key & settings transfer, now with QR",
  "افزونهٔ کامپیوتر": "Desktop extension",
  "صفحهٔ امنیت گفتگوی افزونهٔ CipherGap ۱.۷.۰": "CipherGap 1.7.0 extension chat security screen",
  "صفحهٔ انتخاب پیام‌رسان در CipherGap اندروید ۰.۱.۳": "CipherGap Android 0.1.3 messenger selection screen",
  "خودِ برنامه؛ روی کامپیوتر و اندروید.": "The actual app. On desktop and Android.",
  "در همان پیام‌رسان خودتان": "In the messenger you already use",
  "روی نسخهٔ وب، با حساب فعلی شما.": "On the web version, with your existing account.",
  "بله": "Bale",
  "ایتا": "Eitaa",
  "روبیکا": "Rubika",
  "دسکتاپ": "Desktop",
  "سروش پلاس": "Soroush Plus",
  "از متن شما تا چت": "FROM YOUR TEXT TO YOUR CHAT",
  "شما متن را می‌نویسید.": "You write the message.",
  "CipherGap آن را رمز می‌کند.": "CipherGap encrypts it.",
  "دکمهٔ رمزگذاری CipherGap را می‌زنید، پیام رمز‌شده در همان گفتگو ارسال می‌شود و طرف مقابل آن را با کلید مشترک می‌خواند.": "Press CipherGap’s Encrypt button. The encrypted message travels through the same conversation; your partner reads it with the shared key.",
  "متن یا فایل شما": "Your text or file",
  "پیام را بنویسید یا فایل را از ابزار CipherGap انتخاب کنید.": "Write your message or pick a file with CipherGap’s controls.",
  "رمزگذاری روی دستگاه": "Encrypt on your device",
  "دکمهٔ Encrypt یا Secure files را بزنید.": "Use Encrypt or Secure files.",
  "ارسال در همان چت": "Send in the same chat",
  "متن رمز‌شده یا فایل .cgpe به پیام‌رسان می‌رسد.": "The messenger receives encrypted text or a .cgpe file.",
  "خواندن با کلید مشترک": "Read with the shared key",
  "طرف مقابل با CipherGap پیام را باز می‌کند.": "Your partner opens it with CipherGap.",
  "دکمه‌های معمولی پیام‌رسان، پیام و فایل معمولی می‌فرستند. برای رمزگذاری از ابزارهای CipherGap استفاده کنید.": "The messenger’s regular buttons send regular messages and files. Use CipherGap’s controls to encrypt them.",
  "متن و فایل، با هم": "Messages and files",
  "پیام فارسی، انگلیسی و ایموجی؛ فایل، عکس و صدایی که پس از رمزگشایی باز یا دانلود می‌شوند.": "Persian, English and emoji. Files, images and audio you can open or download after decryption.",
  "هر گفتگو، کلید خودش": "A key for each conversation",
  "از داخل چت کلید مشترک بسازید و کد شش‌رقمی را با طرف مقابل از یک راه مطمئن مقایسه کنید.": "Set up a shared key in the chat and compare the six-digit code with your partner through a trusted channel.",
  "کلیدها را همراه ببرید": "Take your keys with you",
  "پشتیبان رمزدار از همهٔ کلیدها و تنظیمات یا یک چت بگیرید. برای اشتراک یک کلید، QR بسازید یا اسکن کنید.": "Export a password-encrypted backup of all keys and settings or one chat. Share a single key by generating or scanning a QR.",
  "قبل از نصب، داخلش را ببینید": "A LOOK INSIDE BEFORE YOU INSTALL",
  "همین چیزی است که نصب می‌کنید.": "This is what you’ll install.",
  "تصاویر واقعی افزونهٔ ۱.۷.۰ و اندروید ۰.۱.۳، با داده‌های نمایشی در یک گفتگوی آزمایشی. برای دیدن جزئیات، تصویر را باز کنید.": "Actual extension 1.7.0 and Android 0.1.3 screens, with demo data in a test conversation. Open an image to see the details.",
  "باز کردن تصویر: فایل را از همین‌جا رمز کنید": "Open screenshot: Encrypt files from here",
  "فایل را از همین‌جا رمز کنید": "Encrypt files from here",
  "ارسال فایل رمز‌شده و تنظیم دریافت خودکار برای همین گفتگو.": "Encrypted file sending and automatic receiving for this conversation.",
  "باز کردن تصویر: پشتیبان و انتقال کلید": "Open screenshot: Back up and transfer keys",
  "پشتیبان و انتقال کلید": "Back up and transfer keys",
  "خروجی کامل یا یک چت؛ واردکردن پشتیبان و اشتراک کلید با QR.": "Full or single-chat export, backup import and key sharing with QR.",
  "باز کردن تصویر: امنیت چت، روی گوشی": "Open screenshot: Chat security on your phone",
  "امنیت چت، روی گوشی": "Chat security on your phone",
  "همان کلید و تنظیمات گفتگو، داخل برنامهٔ اندروید.": "The same conversation key and settings in the Android app.",
  "باز کردن تصویر: از کامپیوتر به گوشی": "Open screenshot: From desktop to your phone",
  "از کامپیوتر به گوشی": "From desktop to your phone",
  "فرمت مشترک پشتیبان بین اندروید و وب؛ خواندن QR از دوربین یا تصویر.": "A shared backup format across Android and web; read a QR with the camera or from an image.",
  "نسخه و منبع تصاویر": "Screenshot versions & sources",
  "از این دستگاه شروع کنید": "START ON THIS DEVICE",
  "نصب کنید.": "Install it.",
  "بعد، یک کلید مشترک بسازید.": "Then set up a shared key.",
  "شما و طرف مقابل، هر دو CipherGap لازم دارید. در بله، ایتا، تلگرام وب A، روبیکا و سروش پلاس می‌توانید از اندروید و کامپیوتر با هم گفتگو کنید.": "Both you and your partner need CipherGap. On Bale, Eitaa, Telegram Web A, Rubika and Soroush Plus, Android and desktop work together.",
  "فایل‌های همین نسخه، مستقیم از این سایت": "These builds, directly from this site",
  "ریلیز دسکتاپ ۱.۷.۰": "Desktop 1.7.0 release",
  "ریلیز اندروید ۰.۱.۴": "Android 0.1.4 release",
  "مشاهدهٔ SHA-256 فایل‌ها": "View file SHA-256 checksums",
  "کد و راهنمای ساخت در GitHub": "Source & build instructions on GitHub",
  "انتخاب دستگاه یا مرورگر": "Choose a device or browser",
  "برنامهٔ اندروید": "Android app",
  "راهنمای انتقال از نسخهٔ قدیمی": "Migration guide for older builds",
  "CipherGap یک مرورگر برای نسخهٔ وب پیام‌رسان‌هاست. باید داخل خود برنامه وارد حساب پیام‌رسان شوید.": "CipherGap is a browser for web messengers. Sign in to your messenger inside the app.",
  "دانلود APK اندروید": "Download Android APK",
  "ساخت release با امضای اختصاصی و دیباگ خاموش. برای جایگزینی نسخهٔ debug، اول پشتیبان رمزدار بگیرید؛ سپس نسخهٔ قبلی را حذف، این نسخه را نصب و پشتیبان را بازیابی کنید.": "A release build with a dedicated signing key and debugging disabled. To replace a debug build, export a password-encrypted backup first; then uninstall the old app, install this release and restore your backup.",
  "APK را باز و نصب کنید": "Open and install the APK",
  "اگر اندروید اجازه خواست، نصب از مرورگر یا Files را برای همین نصب فعال کنید و سپس خاموش کنید. Play Protect را روشن نگه دارید.": "If Android asks, allow installation from your browser or Files for this installation, then turn it off again. Keep Play Protect enabled.",
  "پیام‌رسان را انتخاب و وارد شوید": "Choose your messenger and sign in",
  "در برنامه، بله، ایتا، Telegram Web A، روبیکا یا سروش پلاس را انتخاب کنید. برنامهٔ اصلی پیام‌رسان تغییری نمی‌کند.": "In the app, choose Bale, Eitaa or Telegram Web A. Your regular messenger app stays as it is.",
  "گفتگو و «امنیت چت» را باز کنید": "Open a conversation and Chat security",
  "بعد از انتخاب مخاطب، Chat security را بزنید. راهنمای ساخت کلید مشترک در بخش بعدی همین صفحه است.": "After choosing a contact, tap Chat security. Follow the shared-key guide in the next section.",
  "اگر WebView سازگار نبود، چه کنم؟": "What if my WebView is incompatible?",
  "اندروید ۸ به بالا برای نصب لازم است؛ WebView هم باید اجرای جداگانه را پشتیبانی کند. آن را از مسیر رسمی دستگاه به‌روز کنید. اگر هشدار باقی ماند، از نسخهٔ کامپیوتر استفاده کنید.": "Installation needs Android 8 or later, and WebView must support isolated execution. Update it through your device’s official channel. If the warning remains, use the desktop extension.",
  "راهنمای کامل اندروید": "Full Android guide",
  "کامپیوتر": "Desktop",
  "افزونه را روی نسخهٔ دسکتاپ مرورگر نصب کنید. دانلود و نصب دستی است.": "Install the extension in your desktop browser. Download it and install manually.",
  "دانلود ZIP افزونه": "Download extension ZIP",
  "ZIP را از حالت فشرده خارج کنید": "Unzip the download",
  "پوشه‌ای را نگه دارید که manifest.json داخل آن است.": "Keep the folder containing manifest.json.",
  "کپی آدرس": "Copy address",
  "کپی": "Copy",
  "صفحهٔ افزونه‌ها را باز کنید": "Open the extensions page",
  "این آدرس را در نوار آدرس مرورگر وارد کنید.": "Paste this address into your browser’s address bar.",
  "افزونه را بارگذاری کنید": "Load the extension",
  "Developer mode را روشن کنید؛ Load unpacked را بزنید و پوشهٔ افزونه را انتخاب کنید.": "Turn on Developer mode, choose Load unpacked and select the extension folder.",
  "صفحهٔ پیام‌رسان را رفرش کنید": "Refresh the messenger page",
  "وارد حساب شوید و یک گفتگو باز کنید. آیکون CipherGap را در نوار ابزار مرورگر باز کنید.": "Sign in and open a conversation. Open the CipherGap icon in your browser toolbar.",
  "دانلود ZIP فایرفاکس": "Download Firefox ZIP",
  "Load Temporary Add-on را بزنید و manifest.json را انتخاب کنید. این نصب با بسته‌شدن Firefox حذف می‌شود.": "Choose Load Temporary Add-on and select manifest.json. This install is removed when Firefox closes.",
  "این آدرس را در نوار آدرس مرورگر وارد کنید. برای Brave از brave://extensions استفاده کنید.": "Paste this address into your browser’s address bar. For Brave, use brave://extensions.",
  "اولین گفتگوی رمز‌شده": "YOUR FIRST ENCRYPTED CONVERSATION",
  "سه قدم، برای هر دو نفر.": "Three steps. For both of you.",
  "این مراحل در برنامهٔ اندروید و افزونه یکی‌اند. لازم نیست دستگاه‌های شما یکسان باشند.": "The steps are the same in the Android app and extension. You don’t need the same kind of device.",
  "درخواست ساخت کلید بدهید": "Start a key exchange",
  "در تب امنیت، «راه‌اندازی چت امن» را بزنید. طرف مقابل درخواست را در گفتگو می‌پذیرد.": "In Security, choose Set up secure chat. Your partner accepts the request in the conversation.",
  "کد شش‌رقمی را مقایسه کنید": "Compare the six-digit code",
  "از تماس مطمئن یا حضوری، کد را روی هر دو دستگاه مقایسه و تأیید کنید. درخواست و کد پس از ۱۵ دقیقه منقضی می‌شوند.": "Compare the code on both devices through a trusted call or in person, then verify it. Requests and codes expire after 15 minutes.",
  "اول یک پیام آزمایشی بفرستید": "Send a test message first",
  "با Encrypt یک پیام کوتاه بفرستید و مطمئن شوید طرف مقابل آن را می‌خواند. بعد، پیام و فایل موردنظرتان را ارسال کنید.": "Send a short message with Encrypt and make sure your partner can read it. Then send your messages and files.",
  "شفاف دربارهٔ حریم خصوصی": "CLEAR ABOUT PRIVACY",
  "رمزگذاری روی دستگاه.": "Encryption on your device.",
  "با محدودیت‌های روشن.": "With clear limits.",
  "جزئیات امنیت در مخزن": "Security details in the repository",
  "CipherGap سرور چت یا محل ذخیرهٔ کلید ندارد": "CipherGap has no chat server or key vault",
  "رمزگذاری و رمزگشایی روی دستگاه انجام می‌شوند. خود پیام‌رسان، پیام رمز‌شده و اطلاعات عادی حساب و گفتگو را دریافت می‌کند.": "Encryption and decryption happen on your device. The messenger receives the encrypted message and ordinary account and conversation metadata.",
  "دستگاه و صفحهٔ پیام‌رسان هم مهم‌اند": "Your device and messenger page matter too",
  "وقتی پیام در صفحهٔ وب باز می‌شود، کد همان پیام‌رسان می‌تواند متن بازشده را بخواند. CipherGap هویت، زمان گفتگو یا دستگاه آلوده را پنهان یا ایمن نمی‌کند.": "Once a message is decrypted on a web page, the messenger’s code can read that plaintext. CipherGap does not hide your identity or chat times, or secure a compromised device.",
  "QR کلید را خصوصی نشان دهید": "Show key QRs privately",
  "هر کسی QR کلید را ببیند می‌تواند کلید را دریافت کند. فایل پشتیبان رمزدار است؛ گذرواژهٔ آن را جدا نگه دارید.": "Anyone who sees a key QR can obtain the key. Backup files are password encrypted; keep their password separately.",
  "پیش از شروع": "BEFORE YOU START",
  "سوال دارید؟": "Questions?",
  "از همین‌جا شروع کنید.": "Start here.",
  "پاسخ‌های کوتاه دربارهٔ نصب، کلیدها و چیزی که CipherGap انجام می‌دهد.": "Short answers about installation, keys and what CipherGap does.",
  "گزارش مشکل در GitHub": "Report an issue on GitHub",
  "CipherGap دقیقاً چیست؟": "What exactly is CipherGap?",
  "یک افزونهٔ کامپیوتر و برنامهٔ اندروید برای رمزگذاری پیام و فایل قبل از ارسال است. گفتگو از نسخهٔ وب پیام‌رسان فعلی شما عبور می‌کند؛ CipherGap روی دستگاه رمزگذاری و رمزگشایی می‌کند.": "A desktop extension and Android app for encrypting messages and files before sending. Your conversation goes through your existing messenger’s web version; CipherGap encrypts and decrypts on your device.",
  "طرف مقابل هم باید نصب کند؟": "Does the other person need it too?",
  "بله. هر دو نفر CipherGap و یک کلید مشترک لازم دارند. در بله، ایتا، تلگرام وب A، روبیکا و سروش پلاس، یک نفر می‌تواند اندروید داشته باشد و دیگری افزونهٔ کامپیوتر.": "Yes. Both people need CipherGap and a shared key. In Bale, Eitaa, Telegram Web A, Rubika and Soroush Plus, one person can use Android and the other a desktop extension.",
  "داخل اپ اصلی بله یا تلگرام کار می‌کند؟": "Does it work inside the regular Bale or Telegram app?",
  "CipherGap در نسخهٔ وب کار می‌کند. روی کامپیوتر، سایت پیام‌رسان را باز می‌کنید؛ روی اندروید، همان سایت داخل مرورگر CipherGap باز می‌شود. برنامهٔ اصلی پیام‌رسان تغییر نمی‌کند.": "CipherGap works in web versions. On desktop, open the messenger website; on Android, that website opens inside CipherGap’s browser. Your regular messenger app is unchanged.",
  "کدام پیام‌رسان‌ها پشتیبانی می‌شوند؟": "Which messengers are supported?",
  "دسکتاپ و اندروید: بله، ایتا، Telegram Web A، روبیکا و سروش پلاس. Telegram Web K و واتساپ پشتیبانی نمی‌شوند.": "Desktop and Android: Bale, Eitaa, Telegram Web A, Rubika and Soroush Plus. Telegram Web K and WhatsApp are not supported.",
  "آدرس ایتا با نام کاربری هم معتبر است؟": "Can Eitaa use a username URL?",
  "بله. نسخهٔ فعلی، هم شناسهٔ عددی مانند #333000 و هم نام کاربری مانند #@mralizohdi را تشخیص می‌دهد.": "Yes. The current version recognizes numeric IDs such as #333000 and usernames such as #@mralizohdi.",
  "روی گوشی جدید، کلیدها را چطور برگردانم؟": "How do I restore keys on another device?",
  "در تب انتقال، با یک گذرواژهٔ حداقل ۱۰ کاراکتری «خروجی همه» بگیرید. در دستگاه دیگر همان فایل و گذرواژه را وارد و بازیابی گفتگوهای اصلی را انتخاب کنید. حساب‌های پیام‌رسان را جداگانه وارد کنید؛ تاریخچه و نشست ورود در پشتیبان نیستند.": "In Transfer, export everything with a password of at least 10 characters. Import the file with the same password on the other device and choose Restore to original chats. Sign in to messenger accounts separately; backups exclude history and login sessions.",
  "یک کلید را چطور با دوستم به اشتراک بگذارم؟": "How do I share one key with my partner?",
  "پشتیبان یک چت بگیرید و طرف مقابل هنگام واردکردن، «استفاده از کلید در گفتگوی فعلی» را انتخاب کند؛ یا QR کلید را خصوصی نشان دهید و با دوربین، تصویر یا متن اسکن‌شده وارد کنید. کلید واردشده به معنی تأیید هویت نیست.": "Export one chat and have your partner choose Use key in current chat when importing. Or show the key QR privately and import it using the camera, an image or scanned text. An imported key does not verify identity.",
  "اگر گذرواژهٔ پشتیبان یا کلید را گم کنم؟": "What if I lose my backup password or key?",
  "CipherGap کلیدها یا گذرواژهٔ پشتیبان را روی سرور نگه نمی‌دارد و نمی‌تواند آن‌ها را بازیابی کند. حذف یا تغییر کلید ممکن است پیام‌های قبلی را غیرقابل‌خواندن کند. یک پشتیبان امن نگه دارید.": "CipherGap does not keep keys or backup passwords on a server and cannot recover them. Deleting or changing a key may make earlier messages unreadable. Keep a secure backup.",
  "دوربین و اعلان‌ها در اندروید چطور کار می‌کنند؟": "How do Android camera access and notifications work?",
  "دوربین فقط با مجوز شما برای اسکن QR در صفحهٔ محلی CipherGap فعال می‌شود؛ پیام‌رسان‌ها و میکروفون دسترسی ندارند. اعلان‌ها اختیاری و عمومی‌اند و فقط وقتی برنامه و صفحه باز هستند کار می‌کنند؛ اعلان پس‌زمینه نداریم.": "The camera is enabled with your permission only for QR scanning in CipherGap’s local screen; messengers and the microphone have no access. Notifications are optional and generic, and work only while the app and page are open. There are no background notifications.",
  "برای iPhone یا Safari نسخه دارید؟": "Is there an iPhone or Safari version?",
  "فعلاً نسخهٔ iOS یا افزونهٔ Safari نداریم. نسخه‌های فعلی، برنامهٔ اندروید و افزونه‌های دسکتاپ Chrome، Chromium و Firefox هستند.": "There is no iOS app or Safari extension yet. Current options are the Android app and desktop Chrome, Chromium and Firefox extensions.",
  "پیام یا فایل معمولی هم خودکار رمز می‌شود؟": "Are ordinary messages or files encrypted automatically?",
  "برای ارسال رمز‌شده باید ابزار CipherGap را انتخاب کنید. دکمه‌های معمولی پیام‌رسان، ارسال معمولی انجام می‌دهند. رمزگشایی و دریافت فایل‌های تازه می‌توانند برای هر چت اختیاری و خودکار باشند.": "Choose CipherGap’s controls to send encrypted content. The messenger’s regular buttons send normally. Decryption and receiving new files can optionally be automatic per chat.",
  "رایگان است؟ حمایت مالی اجباری است؟": "Is it free? Is a donation required?",
  "استفاده از CipherGap رایگان و کد آن باز است. حمایت مالی کاملاً اختیاری است و به توسعه و نگهداری کمک می‌کند.": "CipherGap is free to use and its code is open. Donations are entirely optional and help maintain and improve it.",
  "با همراهی شما ادامه پیدا می‌کند": "HELP KEEP IT GOING",
  "رایگان برای شما.": "Free for you.",
  "با حمایت شما، بهتر برای همه.": "Better for everyone, with your support.",
  "اگر CipherGap برایتان مفید است، می‌توانید به توسعه و نگهداری آن کمک کنید. حمایت مالی اختیاری است.": "If CipherGap helps you, you can support its development and maintenance. Donations are optional.",
  "حمایت مالی در کافیته": "Support on Coffeete",
  "رمزگذاری روی دستگاه شما، برای گفتگوی روزمره.": "On-device encryption for your everyday chats.",
  "لینک‌های پروژه": "Project links",
  "علی شریفی": "Ali Sharify",
  "حمایت مالی": "Support",
  "نمای بزرگ تصویر برنامه": "Full-size app screenshot",
  "بستن تصویر": "Close screenshot",
  "01 / از متن شما تا چت": "01 / FROM YOUR TEXT TO THE CHAT",
  "02 / قبل از نصب، داخلش را ببینید": "02 / LOOK INSIDE BEFORE INSTALLING",
  "03 / از این دستگاه شروع کنید": "03 / START WITH THIS DEVICE",
  "04 / اولین گفتگوی رمز‌شده": "04 / YOUR FIRST ENCRYPTED CHAT",
  "05 / پیش از شروع": "05 / BEFORE YOU BEGIN",
  "کد و راهنمای ساخت در GitHub ↗": "Source & build instructions on GitHub ↗",
  "دانلود APK اندروید ↓": "Download Android APK ↓",
  "راهنمای کامل اندروید ↗": "Full Android guide ↗",
  "1.7.0 / کامپیوتر": "1.7.0 / Desktop",
  "دانلود ZIP افزونه ↓": "Download extension ZIP ↓",
  "دانلود ZIP فایرفاکس ↓": "Download Firefox ZIP ↓",
  "جزئیات امنیت در مخزن ↗": "Security details in the repository ↗",
  "گزارش مشکل در GitHub ↗": "Report an issue on GitHub ↗",
  "حمایت مالی در کافیته ↗": "Support development on Coffeete ↗"
};
